In [1]:
import pandas as pd
import numpy as np

In [2]:
appearences_df = pd.read_csv('../data/baseballdatabank/core/Appearances.csv')
player_df = pd.read_csv('../data/baseballdatabank/core/People.csv')

In [3]:
appearences_df

,yearID,teamID,lgID,playerID,G_all,GS,G_batting,G_defense,G_p,G_c,...,G_2b,G_3b,G_ss,G_lf,G_cf,G_rf,G_of,G_dh,G_ph,G_pr
0,1871,TRO,NaN,abercda01,1,1.0,1,1.0,0,0,...,0,0,1,0,0,0,0,0.0,0.0,0.0
1,1871,RC1,NaN,addybo01,25,25.0,25,25.0,0,0,...,22,0,3,0,0,0,0,0.0,0.0,0.0
2,1871,CL1,NaN,allisar01,29,29.0,29,29.0,0,0,...,2,0,0,0,29,0,29,0.0,0.0,0.0
3,1871,WS3,NaN,allisdo01,27,27.0,27,27.0,0,27,...,0,0,0,0,0,0,0,0.0,0.0,0.0
4,1871,RC1,NaN,ansonca01,25,25.0,25,25.0,0,5,...,2,20,0,1,0,0,1,0.0,0.0,0.0
5,1871,FW1,NaN,armstbo01,12,12.0,12,12.0,0,0,...,0,0,0,0,11,1,12,0.0,0.0,0.0
6,1871,RC1,NaN,barkeal01,1,1.0,1,1.0,0,0,...,0,0,0,1,0,0,1,0.0,0.0,0.0
7,1871,BS1,NaN,barnero01,31,31.0,31,31.0,0,0,...,16,0,15,0,0,0,0,0.0,0.0,0.0
8,1871,FW1,NaN,barrebi01,1,1.0,1,1.0,0,1,...,0,1,0,0,0,0,0,0.0,0.0,0.0
9,1871,BS1,NaN,barrofr01,18,17.0,18,18.0,0,0,...,1,0,0,13,0,4,17,0.0,0.0,0.0
10,1871,CL1,NaN,bassjo01,22,22.0,22,22.0,0,1,...,0,0,22,0,0,0,0,0.0,0.0,0.0
11,1871,CL1,NaN,battijo01,1,1.0,1,1.0,0,0,...,0,0,0,0,0,1,1,0.0,0.0,0.0
12,1871,WS3,NaN,bealsto01,10,10.0,10,10.0,0,0,...,2,0,0,4,0,4,8,0.0,0.0,0.0
13,1871,TRO,NaN,beaveed01,3,3.0,3,3.0,0,0,...,3,0,0,0,0,0,0,0.0,0.0,0.0
14,1871,PH1,NaN,bechtge01,20,19.0,20,20.0,3,0,...,0,3,0,1,3,11,15,0.0,0.0,0.0
15,1871,TRO,NaN,bellast01,29,29.0,29,29.0,0,0,...,0,28,1,0,0,0,0,0.0,0.0,0.0
16,1871,PH1,NaN,berkena01,1,1.0,1,1.0,0,0,...,0,0,0,0,0,1,1,0.0,0.0,0.0
17,1871,PH1,NaN,berryto01,1,1.0,1,1.0,0,0,...,0,0,0,0,0,1,1,0.0,0.0,0.0
18,1871,WS3,NaN,berthha01,17,17.0,17,17.0,0,1,...,5,0,0,11,1,0,12,0.0,0.0,0.0
19,1871,FW1,NaN,biermch01,1,1.0,1,1.0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
20,1871,RC1,NaN,birdge01,25,25.0,25,25.0,0,0,...,0,0,0,1,25,0,25,0.0,0.0,0.0
21,1871,BS1,NaN,birdsda01,29,29.0,29,29.0,0,7,...,0,0,0,0,0,27,27,0.0,0.0,0.0
22,1871,WS3,NaN,brainas01,30,30.0,30,30.0,30,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
23,1871,CH1,NaN,brannmi01,3,3.0,3,3.0,0,0,...,0,3,0,0,0,0,0,0.0,0.0,0.0
24,1871,WS3,NaN,burrohe01,12,11.0,12,12.0,0,0,...,1,5,0,4,0,4,8,0.0,0.0,0.0
25,1871,FW1,NaN,careyto01,19,19.0,19,19.0,0,0,...,19,0,0,0,0,0,0,0.0,0.0,0.0
26,1871,CL1,NaN,carleji01,29,29.0,29,29.0,0,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
27,1871,BS1,NaN,conefr01,19,18.0,19,19.0,0,0,...,0,0,0,18,0,1,19,0.0,0.0,0.0
28,1871,TRO,NaN,connone01,7,7.0,7,7.0,0,0,...,0,0,0,0,0,3,3,0.0,0.0,0.0
29,1871,TRO,NaN,cravebi01,27,27.0,27,27.0,0,3,...,18,0,4,0,0,1,1,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105759,2018,MIA,NL,wittgni01,32,0.0,32,32.0,32,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105760,2018,COL,NL,wolteto01,74,56.0,74,66.0,0,64,...,2,1,0,2,0,0,2,0.0,6.0,2.0
105761,2018,SLN,NL,wongko01,127,98.0,127,119.0,0,0,...,119,0,0,0,0,0,0,0.0,9.0,1.0
105762,2018,LAN,NL,woodal02,33,27.0,31,33.0,33,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105763,2018,LAA,AL,woodbl01,13,0.0,0,13.0,13,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105764,2018,TBA,AL,woodhu01,31,8.0,4,29.0,29,0,...,0,0,0,0,0,0,0,1.0,0.0,2.0
105765,2018,MIL,NL,woodrbr01,19,4.0,19,19.0,19,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105766,2018,BOS,AL,workmbr01,43,0.0,4,43.0,43,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105767,2018,NYN,NL,wrighda03,2,1.0,2,1.0,0,0,...,0,1,0,0,0,0,0,0.0,1.0,0.0
105768,2018,ATL,NL,wrighky01,4,0.0,4,4.0,4,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105769,2018,BAL,AL,wrighmi01,48,2.0,3,48.0,48,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105770,2018,BOS,AL,wrighst01,20,4.0,2,20.0,20,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105771,2018,BAL,AL,wynnsau01,42,33.0,42,41.0,0,41,...,0,0,0,0,0,0,0,1.0,2.0,1.0
105772,2018,BAL,AL,yacabji01,12,7.0,0,12.0,12,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105773,2018,TBA,AL,yarbrry01,38,6.0,3,38.0,38,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105774,2018,SDN,NL,yateski01,65,0.0,60,65.0,65,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105775,2018,MIL,NL,yelicch01,147,144.0,147,145.0,0,0,...,0,0,0,90,20,75,145,0.0,2.0,0.0
105776,2018,LAA,AL,youngch04,56,32.0,56,48.0,0,0,...,0,0,0,13,17,20,48,1.0,5.0,8.0
105777,2018,LAA,AL,younger03,41,30.0,41,37.0,0,0,...,0,0,0,13,24,0,37,0.0,5.0,2.0
105778,2018,CHN,NL,zagunma01,5,0.0,5,1.0,0,0,...,0,0,0,0,0,1,1,0.0,4.0,0.0
105779,2018,MIL,NL,zagurmi01,2,0.0,2,2.0,2,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105780,2018,NYN,NL,zamorda01,16,0.0,15,16.0,16,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105781,2018,CHN,NL,zastrro01,6,0.0,6,6.0,6,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105782,2018,ARI,NL,zieglbr01,29,0.0,27,29.0,29,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105783,2018,MIA,NL,zieglbr01,53,0.0,49,53.0,53,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105784,2018,CLE,AL,zimmebr01,34,29.0,34,34.0,0,0,...,0,0,0,0,34,0,34,0.0,2.0,0.0
105785,2018,DET,AL,zimmejo02,25,25.0,2,25.0,25,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105786,2018,WAS,NL,zimmery01,85,72.0,85,73.0,0,0,...,0,0,0,0,0,0,0,0.0,13.0,0.0
105787,2018,CHN,NL,zobribe01,139,108.0,139,125.0,0,0,...,63,0,0,43,0,61,84,1.0,22.0,0.0
105788,2018,SEA,AL,zuninmi01,113,102.0,113,111.0,0,111,...,0,0,0,0,0,0,0,1.0,7.0,0.0

In [4]:
appearences_df[appearences_df.playerID == 'zieglbr01']

,yearID,teamID,lgID,playerID,G_all,GS,G_batting,G_defense,G_p,G_c,...,G_2b,G_3b,G_ss,G_lf,G_cf,G_rf,G_of,G_dh,G_ph,G_pr
91407,2008,OAK,AL,zieglbr01,47,0.0,3,47.0,47,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
92795,2009,OAK,AL,zieglbr01,69,0.0,4,69.0,69,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
94151,2010,OAK,AL,zieglbr01,64,0.0,6,64.0,64,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
95540,2011,ARI,NL,zieglbr01,23,0.0,23,23.0,23,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
95541,2011,OAK,AL,zieglbr01,43,0.0,4,43.0,43,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
96948,2012,ARI,NL,zieglbr01,77,0.0,73,77.0,77,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
98356,2013,ARI,NL,zieglbr01,78,0.0,75,78.0,78,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
99790,2014,ARI,NL,zieglbr01,68,0.0,64,68.0,68,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
101272,2015,ARI,NL,zieglbr01,66,0.0,63,66.0,66,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
102755,2016,ARI,NL,zieglbr01,36,0.0,34,36.0,36,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
102756,2016,BOS,AL,zieglbr01,33,0.0,1,33.0,33,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
104249,2017,MIA,NL,zieglbr01,53,0.0,51,53.0,53,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105782,2018,ARI,NL,zieglbr01,29,0.0,27,29.0,29,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0
105783,2018,MIA,NL,zieglbr01,53,0.0,49,53.0,53,0,...,0,0,0,0,0,0,0,0.0,0.0,0.0

In [5]:
zieg = player_df[player_df.playerID == 'zieglbr01']

In [6]:
print(zieg)

        playerID  birthYear  birthMonth  birthDay birthCountry birthState  \
19758  zieglbr01     1979.0        10.0      10.0          USA         KS

      birthCity  deathYear  deathMonth  deathDay  ... nameLast     nameGiven  \
19758     Pratt        NaN         NaN       NaN  ...  Ziegler  Brad Gregory

      weight height bats throws       debut   finalGame   retroID    bbrefID
19758  220.0   76.0    R      R  2008-05-31  2018-09-29  ziegb001  zieglbr01

[1 rows x 24 columns]

In [7]:
#appearences_copy = appearences_df

In [8]:
#merged = appearences_df.merge(right=appearences_copy, right_on=['playerID', 'yearID'], left_on=['playerID', 'yearID'])

In [18]:
appearences_hash = {}
for index, row in appearences_df.iterrows():
    key = '{}_{}'.format(row.playerID, row.yearID)
    if key not in appearences_hash:
        appearences_hash[key] = 1
    else:
        appearences_hash[key] += 1

In [28]:
more_than_once = {}
pid_yearid = []
for key, value in appearences_hash.items():
    if value >= 2:
        more_than_once[key] = value
        pid_yearid.append(key.split('_'))

In [42]:
multiple_df = pd.DataFrame(pid_yearid, columns=['playerID', 'yearID'])
#convert to numerics
multiple_df['yearID'] = multiple_df['yearID'].astype(np.int64)

In [43]:
batting_df = pd.read_csv('../data/baseballdatabank/core/Batting.csv')
display(batting_df.dtypes)
display(multiple_df.dtypes)

playerID     object
yearID        int64
stint         int64
teamID       object
lgID         object
G             int64
AB            int64
R             int64
H             int64
2B            int64
3B            int64
HR            int64
RBI         float64
SB          float64
CS          float64
BB            int64
SO          float64
IBB         float64
HBP         float64
SH          float64
SF          float64
GIDP        float64
dtype: object

playerID    object
yearID       int64
dtype: object

In [45]:
multiple_df_batting = multiple_df.merge(right=batting_df, on=['playerID', 'yearID'], how='left')
multiple_df_batting.tail(20)

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
15279,turneja01,2018,1,MIA,NL,4,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15280,turneja01,2018,2,DET,AL,1,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15281,valerbr01,2018,1,LAN,NL,20,29,4,5,0,...,4.0,0.0,0.0,4,4.0,0.0,0.0,1.0,0.0,0.0
15282,valerbr01,2018,2,BAL,AL,12,35,4,10,0,...,4.0,1.0,0.0,3,9.0,0.0,0.0,1.0,2.0,0.0
15283,vastoje01,2018,1,COL,NL,1,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15284,vastoje01,2018,2,KCA,AL,5,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15285,ventejo01,2018,1,TBA,AL,22,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15286,ventejo01,2018,2,ATL,NL,28,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15287,villajo01,2018,1,MIL,NL,87,257,26,67,10,...,22.0,14.0,2.0,19,80.0,0.0,2.0,0.0,1.0,9.0
15288,villajo01,2018,2,BAL,AL,54,209,28,54,4,...,24.0,21.0,3.0,22,58.0,0.0,3.0,1.0,1.0,4.0
15289,voitlu01,2018,1,SLN,NL,8,11,2,2,0,...,3.0,0.0,0.0,2,4.0,0.0,0.0,0.0,0.0,0.0
15290,voitlu01,2018,2,NYA,AL,39,132,28,44,5,...,33.0,0.0,0.0,15,39.0,0.0,1.0,0.0,0.0,3.0
15291,warread01,2018,1,NYA,AL,24,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15292,warread01,2018,2,SEA,AL,23,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15293,webbty01,2018,1,SDN,NL,4,1,0,0,0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
15294,webbty01,2018,2,SLN,NL,18,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15295,wislema01,2018,1,ATL,NL,7,8,0,0,0,...,0.0,0.0,0.0,0,4.0,0.0,0.0,1.0,0.0,0.0
15296,wislema01,2018,2,CIN,NL,11,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15297,zieglbr01,2018,1,MIA,NL,53,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
15298,zieglbr01,2018,2,ARI,NL,29,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0